name: Unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Install Client Dependencies
        run: npm install --prefix client

      - name: Run tests with coverage
        run: npm run client-test

      - name: Upload coverage to Codecov
        run: npm run coverage:upload
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
